server:
  port: 8081 # Usando 8081 para não conflitar com o Viapro ERP que deve estar na 8080

spring:
  application:
    name: sistema-pedidos-satelite
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bonfire_pedidos_db
    username: postgres
    password: Artorias275018!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Cria e atualiza as tabelas automaticamente no inicio do dev
    show-sql: true # Mostra as queries no console para facilitar o debug
    properties:
      hibernate:
        format_sql: true